listener 1883
allow_anonymous true

# Pour la démo — en production : désactiver allow_anonymous et configurer TLS
# listener 8883
# cafile   /mosquitto/certs/ca.crt
# certfile /mosquitto/certs/server.crt
# keyfile  /mosquitto/certs/server.key
# require_certificate true
